version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data:rw
  django:
    build: .
    command: bash -c "sleep 5s && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/core:/src
    ports:
      - 8000:8000
    depends_on:
      - db
