version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data:rw
  django:
    build: .
    command: bash -c "sleep 5s && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
    depends_on:
      - db
  celery:
    restart: always
    build: .
    command: celery -A core worker -l info -B
    volumes:
      - ./src:/src
    environment:
      - C_FORCE_ROOT=true
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - rabbit
  rabbit:
    restart: always
    image: rabbitmq:alpine
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=diploma
      - RABBITMQ_DEFAULT_PASS=diploma
      - RABBITMQ_DEFAULT_VHOST=diploma