# Generated by Django 2.1.7 on 2019-04-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_assistant',
        ),
    ]
