# Generated by Django 2.1.7 on 2019-05-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190421_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparticipant',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
