# Generated by Django 2.1.7 on 2019-05-17 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('You have many requests for this course, please follow the link to view them', 'You have many requests for this course, please follow the link to view them'), ('Your submission has been graded, go over the link to see the submission results', 'Your submission has been graded, go over the link to see the submission results'), ('You have new assignment to do', 'You have new assignment to do')], max_length=255)),
                ('seen', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='courseparticipant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
