# Generated by Django 2.1.7 on 2019-05-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='folder_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='folder_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
