# Generated by Django 2.1.7 on 2019-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190517_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='git_fork_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
