# Generated by Django 2.1.7 on 2019-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190503_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='task',
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='git_repository_name',
            field=models.CharField(default='wtf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='testfile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
