# Generated by Django 2.1.7 on 2019-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_assignment_git_fork_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='task',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
